## Tarea. Titanic
### Ingenieria de Datos
#### Alan Josue Solano Perez - 16 Abril 2026

### Instrucciones:
Analiza los datos del dataframe titanic.csv responde las siguientes preguntas:

    • Identifica los nombres de las personas que iban en primera clase ordenadas alfabéticamente.
    • Cuál es el porcentaje de personas que murieron?
    • Cuál es porcentaje de personas que sobrevivieron y ordenarlas por clase?
    • Estima el promedio de edad de las personas a bordo del barco?
    • Cuál es la edad media de las mujeres que viajaban en cada clase?
    • Indica cuál el porcentaje de menores y mayores de edad que sobrevivieron en cada clase.
    
Distingue los datos, la información, el conocimiento y la sabiduría de los siguientes datos a desarrolar:

    • Gráfica del porcentaje de menores y mayores de edad que sobrevivieron por clase
    • Gráfica de la edad media de las mujeres y niños que viajaban en cada clase
    • Gráfica del porcentaje de personas que sobrevivieron
    • Gráfica del porcentaje de personas que murieron

In [1]:
# Importacion de librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("data/titanic.csv", index_col = "PassengerId")
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# Filtramos por nombre alfabeticamente
df.sort_values(by="Name")
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
# Limpiamos la db
df_clean = df.dropna()
display(df_clean.head())
# Revisamos si quedaron valores vacios
df_clean.isna().sum()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Cabin       0
Embarked    0
dtype: int64

In [20]:
# Porcentaje de de supervivientes
survived_per = df_clean["Survived"].mean()
survived_per = survived_per*100
print(f'El porcentaje de supervivientes fue de {survived_per:.2f}%')

El porcentaje de supervivientes fue de 67.21%